### ISSUE TITLE
Trello securityDefinitions etc

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/unofficial_openapi_specs#11]
Moving issue to relevant repo.

@bobby-brennan wrote

> Would suggest moving the Trello spec to unofficial-api-specs as the original doesn't seem to be maintained. If you do I'll submit a PR there.
OAuth2 definition should be removed as Trello only supports OAuth1
api_key name should be key
should also have api_token as both key and token are needed
Correct secDefs:

```json
{
  "securityDefinitions": {
    "api_key": {
      "in": "header",
      "name": "key",
      "type": "apiKey"
    },
    "api_token": {
      "type": "apiKey",
      "in": "query",
      "name": "token"
    }
  }
}
```

**Comment by MikeRalphson** [comment]
Thanks @bobby-brennan after PR #13 can we close this?

**Comment by MikeRalphson** [comment]
@bobby-brennan it looks like each occurrence of `trello_auth` needs patching to use one or both of the new apiKey securityDefinitions. Is that something you can do with a search and replace?

**Comment by rbren** [comment]
A little vim-fu:

```
%s/trello_auth:\n\(\s\+- '.*'\n\)\+/api_key: []\r        - api_token: []\r/g
```

https://github.com/APIs-guru/unofficial_openapi_specs/pull/14

**Comment by MikeRalphson** [comment]
Trello updated in the main repo.

**Comment by rbren** [comment]
Thanks!

**Comment by MikeRalphson** [comment]
No, thank you. Are we ok to close this issue now?

**Comment by rbren** [comment]
Looks good to me
